const ID_LENGTH = 35; // Length of IDs
const STAGE_DESCRIPTION_MAX_LENGTH = 250;
const STAGE_TITLE_LENGTH = 250;
const DYNAMO_CONFIG = {};

export {
  ID_LENGTH,
  STAGE_DESCRIPTION_MAX_LENGTH,
  STAGE_TITLE_LENGTH,
  DYNAMO_CONFIG,
};
