const APPLICANT_ID_LENGTH = 20;
const STAGE_DESCRIPTION_MAX_LENGTH = 250;
const STAGE_TITLE_MAX_LENGTH = 250;
const DYNAMO_CONFIG = { region: "us-east-1" };
const DYNAMO_TABLE_NAME = `OpenATS`;
const FIRST_NAME_MAX_LENGTH = 50;
const LAST_NAME_MAX_LENGTH = 50;
export {
  APPLICANT_ID_LENGTH,
  STAGE_DESCRIPTION_MAX_LENGTH,
  STAGE_TITLE_MAX_LENGTH,
  DYNAMO_CONFIG,
  DYNAMO_TABLE_NAME,
  FIRST_NAME_MAX_LENGTH,
  LAST_NAME_MAX_LENGTH,
};
